version: "3.9"
services:
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        volumes:
            - ./.volumes/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234567
            - POSTGRES_DB=culturedge
    backend:
        image: afilipovski/api
        container_name: backend
        build:
            context: ./microservice-architecture/api-gateway
        ports:
            - "9090:9090"
        depends_on:
            - feedback
            - photo
            - heritage
    feedback:
        image: afilipovski/feedback
        container_name: feedback
        build:
            context: ./microservice-architecture/feedback-microservice
        ports:
            - "1111:1111"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/culturedge
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1234567
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    photo:
        image: afilipovski/photo
        container_name: photo
        build:
            context: ./microservice-architecture/photo-microservice
        volumes:
            - ./.volumes/images:/app/images
        ports:
            - "2222:2222"
    heritage:
        image: afilipovski/heritage
        container_name: heritage
        build:
            context: ./microservice-architecture/heritage-microservice
        ports:
            - "3333:3333"
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/culturedge
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1234567
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    culturedge-front:
        image: afilipovski/culturedge-front-d4
        container_name: culturedge-front
        build:
            context: ./culturedge-front
        ports:
            - "80:80"
        depends_on:
            - backend