apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: culturedge
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNDU2Nw==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: culturedge
data:
  POSTGRES_DB: "culturedge"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: culturedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: afilipovski/api-gateway:latest-amd64
          ports:
            - containerPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  namespace: culturedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: afilipovski/feedback-microservice:latest-amd64
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/culturedge
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: 1111

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo
  namespace: culturedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo
  template:
    metadata:
      labels:
        app: photo
    spec:
      containers:
        - name: photo
          image: afilipovski/photo-microservice:latest-amd64
          ports:
            - containerPort: 2222
          volumeMounts:
            - name: image-storage
              mountPath: /app/images
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-storage-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heritage
  namespace: culturedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heritage
  template:
    metadata:
      labels:
        app: heritage
    spec:
      containers:
        - name: heritage
          image: afilipovski/heritage-microservice:latest-amd64
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/culturedge
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          ports:
            - containerPort: 3333

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: culturedge-front
  namespace: culturedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: culturedge-front
  template:
    metadata:
      labels:
        app: culturedge-front
    spec:
      containers:
        - name: culturedge-front
          image: afilipovski/culturedge-front:latest-amd64
          ports:
            - containerPort: 80